### ISSUE TITLE
State supplied to action lifecycle hooks is stale

### ISSUE THREAD

**Issue by djmccormick** [vigetlabs/microcosm#132]
We're running into some confusion with Microcosm v10.0.0-beta3 and I'm unsure if I'm using the library incorrectly or perhaps it's just a symptom of playing with beta software. Strangely, I don't seem to see this behavior in the examples. Thanks in advance for any guidance!

### Results:

	listLoading received 0 and state is actually 0.
	listCompleted received 0 and state is actually a.
	listLoading received c and state is actually c.
	listCompleted received c and state is actually a.
	listLoading received c and state is actually c.
	listCompleted received c and state is actually a.

I expected the received and actual values to match.

### Code:

	import Microcosm from 'microcosm';
	import axios from 'axios';

	/******************************************************************
	 * Action
	 * ***************************************************************/

	function list () {
		return function (action) {
			action.open();

			let cancelled = false;
			action.on('cancel', () => cancelled = true);

			axios.get('https://jsonplaceholder.typicode.com/posts')
				.then(response => {
					if (!cancelled) action.close(response);
				})
				.catch(response => {
					if (!cancelled) action.reject(response);
				});
		}
	}

	/******************************************************************
	 * Store
	 * ***************************************************************/

	const Store = {
		getInitialState() {
			return '0';
		},

		register() {
			return {
				[list.open]: this.listLoading,
				[list.done]: this.listCompleted,
				[list.failed]: this.listFailed,
				[list.cancelled]: this.listCancelled
			};
		},

		listLoading(state) {
			console.log(`listLoading received ${state} and state is actually ${app.state.widgets}.`);

			return 'a';
		},

		listCancelled(state) {
			console.log(`listCancelled received ${state} and state is actually ${app.state.widgets}.`);

			return 'b';
		},

		listCompleted(state) {
			console.log(`listCompleted received ${state} and state is actually ${app.state.widgets}.`);

			return 'c';
		},

		listFailed(state) {
			console.log(`listFailed received ${state} and state is actually ${app.state.widgets}.`);

			return 'd';
		}
	};

	/******************************************************************
	 * Bootstrapping
	 * ***************************************************************/

	class App extends Microcosm {
		constructor() {
			super();

			this.addStore('widgets', Store);
		}
	}

	const app = new App();

	/******************************************************************
	 * Run action
	 * ***************************************************************/

	app.push(list);
	setTimeout(() => {
		app.push(list);

		setTimeout(() => {
			app.push(list);
		}, 1000);
	}, 1000);

Runnable repo here (`npm install && npm start`): https://github.com/Torchlite/microcosm-test

**Comment by nhunzaker** [comment]
Wow. Awesome issue write up! Thank you! I'll dig into this now.

**Comment by nhunzaker** [comment]
Ah got it (I think). @ltk this is something that we really need to nail down in our docs.

**The short answer:**

Microcosm actions are kept in a tree data structure that gets reduced into application state every time an action makes a change. When `list` moves into `done` or `failed`, the `open` state is no longer within that history, so it never occurs. 

**The long answer:**

Store handlers are isolated instructions for processing the given state of an action (`loading`, `cancelled`, `done`, etc...). They won't know about prior states, or have much context other than how they respond to the state an action is in.

When an action is pushed, it gets appended to an internal tree data structure:

![history](https://cloud.githubusercontent.com/assets/590904/17955179/1cb3a04e-6a35-11e6-9d3b-9ab17a0da1d1.gif)

(visualized via [`microcosm-debugger`](https://github.com/vigetlabs/microcosm-debugger))

As actions change state, Microcosm runs through this tree again, executing store handlers on the new state of the tree. So what's happening here is that the `list` action is no longer in the `open` state, moving to `done` or `failed`. The store never gets a request to call the loading state, as if it never occurred.

We've found this to be super helpful for optimistic updates, you get clean up for free, and that it totally eliminates race conditions when determining the proper state for numerous outstanding requests (since actions don't have to worry about cleaning up their own mess). But it can be confusing... I would love to figure out the best way to communicate how this all works.

_aside_: When an action is marked for clean up (via `close`, `reject`, or `cancel`), the final state gets merged into a cache for performance. This is adjustable by passing a `{ maxHistory: n }` option when instantiating Microcosm.

**Comment by djmccormick** [comment]
@nhunzaker, thank you for taking the time to explain so thoroughly. I really appreciate it.

Even before I understood, this was the only Flux-like implementation I've found that actually accounts for the many states of asynchronous activities. Now, understanding the tree, I see the real power of what you guys are making here. Mind = blown. Love it!
