### ISSUE TITLE
Domain and Effect creation

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/microcosm#254]
> *Leo*: Why is there no code sample for addDomain like there is for addEffect ?

> *Nate*: There is no reason. I'll add an issue for this. We also need to better describe how you can create domains and effects (simple objects vs classes)

**Comment by keturn** [comment]
👍 for highlighting "simple objects vs classes," I tripped over that one for a while.

**Comment by nhunzaker** [comment]
@keturn I've sent out a PR that documents the creation process here: 
https://github.com/vigetlabs/microcosm/pull/275

I'm happy to help clear things up. Would you be willing to share what tripped you up, so I can make sure to cover it in the docs?

**Comment by keturn** [comment]
The way I remember it is that I thought "both Domain and Effect have `register` methods that refer to methods on `this.`, I'll make them both classes",

and then things confusingly Did Not Work until I made the Domain a simple object instead. 

However, the documentation in this patch says you can use either approach with either thing. Is that a change since version 11?

**Comment by nhunzaker** [comment]
Hmmm. It looks like we added it in 10.2.0:
https://github.com/vigetlabs/microcosm/blob/master/CHANGELOG.md#1020

So I'm not sure. We use the `class` form on a project that's still on 11.x without a problem.

Either way, I am glad that the class form jives with how you were thinking about Domains and Effects!

**Comment by nhunzaker** [comment]
Just merged a related PR. I'm going to close this out.
